config/routes.rb
Rails.application.routes.draw do
 root to: 'toppages#index'
 
 get 'login',to: 'sessions#new'
 post 'login',to: 'sessions#create'
 delete 'logout',to: 'sessions#destroy'
 
 get 'signup',to: 'users#new'
 resources :users,only: [:create,:show]
 resources :questions,only: [:new,:create,:destroy,:show] do
   get :search , on: :collection
  end 
  resources :answers,only: [:create,:destroy]
 resources :password_resets,only: [:new,:create,:edit,:update]
 
resources :cakes,only: [:create,:show,:edit,:update]
resources :mokuhyous,only: [:new,:create,:edit,:update]
end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :question
  
  validates :content,length: {maximum: 255}
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cake.rb
class Cake < ApplicationRecord
  belongs_to :user
  
  
  
  validates :try ,length: {maximum: 255}
  validates :content,length: {maximum: 255}
  validates :impression,length: {maximum: 255}
  

  
  private
  def once_a_day
      if current_user.cakes.exists?(created_at: Time.zone.now.all_day)
          errors.add(:time,'重複しています')
      end 
  end 
end

app/models/mokuhyou.rb
class Mokuhyou < ApplicationRecord
  belongs_to :user
  
 validates :content ,length: {maximum: 255}
end

app/models/question.rb
class Question < ApplicationRecord
   is_impressionable counter_cache: true
   
   validates :content,length: {maximum: 255}
  
  belongs_to :user
   
  has_many :answers
end

app/models/user.rb
class User < ApplicationRecord
      before_save { self.email.downcase! }
  validates :name, presence: true, length: { maximum: 50 }
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i },
                    uniqueness: { case_sensitive: false }
  has_secure_password
  
  has_many :questions
  has_many :cakes
  has_many :mokuhyous
end

app/controllers/answers_controller.rb
  class AnswersController < ApplicationController
   
    def create
       @question = Question.find(params[:question_id])
       @answer = @question.answers.build(answer_params)
       @answers = @question.answers
      if @answer.save
        flash[:success]="投稿しました"
        redirect_to @question
      else
        flash.now[:danger]="投稿できませんでした"
      render  "questions/show"
      end 
    end
  
    def destroy
    end
    
  private
  def answer_params
    params.require(:answer).permit(:name,:content)
  end 
    
  end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    
 private
     def current_user
       @current_user ||=User.find_by(id: session[:user_id])
     end 
  
     def logged_in?
       !!current_user
     end 
    
     def requier_user_logged_in
       unless logged_in?
         redirect_to root_url
       end 
     end  
    
end

app/controllers/cakes_controller.rb
class CakesController < ApplicationController
    def create
      @user = current_user
    @sleep = current_user.cakes.build(cakes_params)
    if @sleep.save
      flash[:success]="投稿しました"
      redirect_to cake_path(@user)
    else
      flash[:danger]="投稿できませんでした:投稿は１日一回までです。"
      redirect_to user_path(@user)
    end 
  end
  
  def show
    @sleeps = current_user.cakes
   i = 0
   @sleeps.each do|sleep|
     @sleep_time = i += sleep.time / @sleeps.count
   end 
   def edit
     @sleep = Cake.find(params[:id])
   end 
   
   
   def update
       
     @sleep = current_user.cakes.find(params[:id])
     
     if @sleep.update(cakes_params)
       flash[:success]="編集しました"
       redirect_to cake_path(current_user)
     else
       flash.now[:danger]="編集できませんでした"
       render :edit
     end 
   end 
  
  end 
  private
  def cakes_params
    params.require(:cake).permit(:time,:try,:impression,:content)
  end 
 
end

app/controllers/mokuhyous_controller.rb
class MokuhyousController < ApplicationController
  def new
    @mokuhyou = current_user.mokuhyous.build
  end

  def create
    @mokuhyou = current_user.mokuhyous.build(mokuhyou_params)
    if @mokuhyou.save
      flash[:success]="投稿しました"
      redirect_to user_path(current_user)
    else
      flash[:danger]="投稿に失敗しました"
      render :new
    end 
  end

  def edit
  end

  def update
  end

private
  def mokuhyou_params 
     params.require(:mokuhyou).permit(:content)
  end 
  
  
end

app/controllers/password_resets_controller.rb
class PasswordResetsController < ApplicationController
  def new
  end
  def create
    @user = User.find_by(email: params[:password_reset][:email].downcase)
    if @user
      @user.create_reset_digest
      @user.send_password_reset_email
      flash[:success]="パスワードを変更する為のメールを送りました"
    　redirect_to root_url
    else
    　  flash.now[:danger]="メールアドレスが違います"
    　  render :new
    end 
  end 
  
  def edit
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :requier_user_logged_in, only: [:new]
  def new
    @question = current_user.questions.build
  end
  def show
    @question = Question.find(params[:id])
    @answer = @question.answers.build
    @answers = @question.answers
    impressionist(@question, nil)
  end 
  
  def create
    @question = current_user.questions.build(question_params)
    if @question.save
      flash[:success]="投稿しました"
      redirect_to current_user
    else
      flash.now[:danger]="投稿できませんでした"
      render :new
    end 
  end

  def destroy
    @question = Question.find(params[:id])
   @question.destroy
   
    flash[:success]="削除しました"
    redirect_to root_url
  end
  
  def search
    if params[:content].present?
     @questions = Question.where('content LIKE ?',"%#{params[:content]}%")
    else
      @questions =Question.all
    
    end 
  end 

  private
  
  def question_params
    params.require(:question).permit(:content)
  end 
end 

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    email = params[:session][:email].downcase
    password = params[:session][:password]
    if login(email,password)
      flash[:success]="ログインしました"
      redirect_to root_url
    else
      flash.now[:danger]="ログインに失敗しました"
      render :new
    end 
  end

  def destroy
    session[:user_id] = nil
    flash[:success]="ログアウトしました"
    redirect_to root_url
  end
  
  private
  def login(email,password)
    @user = User.find_by(email: email)
    if @user && @user.authenticate(password)
      session[:user_id] = @user.id
      return true
    else
      return false
    end 
  end 
  
 
end

app/controllers/toppages_controller.rb
class ToppagesController < ApplicationController
  def index
    @questions = Question.all
    @rank_questions = Question.order(impressions_count: 'desc')
    
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  def new
    @user = User.new
  end
  def show
    @user = User.find(params[:id])
    @questions = @user.questions
    @sleep = @user.cakes.build
     @mokuhyou = @user.mokuhyous.last
 
   @todays_sleep = @user.cakes.last(2)[0]
  
  end 

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:success]="登録できました"
      redirect_to login_path
    else
      flash.now[:danger]="登録できませんでした"
      render :new
    end 
  end
  
  private
  def user_params
    params.require(:user).permit(:name,:email,:password,:password_confirmation)
  end 

   
end

app/helpers/application_helper.rb
module ApplicationHelper
   
end

app/helpers/sessions_helper.rb
module SessionsHelper
     def current_user
       @current_user ||=User.find_by(id: session[:user_id])
     end 
  
     def logged_in?
       !!current_user
     end 
    
     def requier_user_logged_in
       unless logged_in?
         redirect_to root_url
       end 
     end  
end

app/views/cakes/edit.html.erb
<%= form_with(model: @sleep,local: true)do|f|%>
  <%= f.label :time, '睡眠時間' %>
  <%= f.text_field :time %>
  <%= f.label :try, '試したことジ' %>
  <%= f.text_field :try %>
  <%= f.label :impression, '感想' %>
  <%= f.text_field :impression %>
  <%= f.label :content, '気づき' %>
  <%= f.text_field :content %>
  <%= hidden_field_tag :question_id,current_user.id %>
  
  <%= f.submit '更新' %>
<% end %>
<%= link_to '睡眠記録に戻る',cakes_path(@current_user)%>

app/views/cakes/show.html.erb
<div class="sesese">
    <div class="text-danger bg-light d-inline">今月の平均睡眠時間<%= @sleep_time %>時間</div>
<div class="overflow-auto " style="height:700px; width:1640px;">
<table class="table table-warning">
    <thead>
        <tr>
            <th>投稿日</th>
            <th>睡眠時間</th>
            <th>試したこと</th>
            <th>感想</th>
            <th>気づき</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        <% @sleeps.order(created_at: 'DESC').each do|sleep| %>
        <tr>
            <td><div class="aaaaa"><%= sleep.created_at.to_s(:datetime_jp) %></div></td>
            <td><div class="aaaaa"><%= sleep.time %></div></td>
            <td><div class="aaaaa"><%= sleep.try %></div></td>
            <td><div class="aaaaa"></div><%= sleep.impression %></div></td>
            <td><div class="aaaaa"><%= sleep.content %></div></td>
            <td><div class="btn btn-light"><%= link_to '編集',edit_cake_path(sleep)%></div></td>
        </tr>
        <% end %>
    </tbody>
</table>
</div>
</div>

app/views/layouts/_error_messages.html.erb
<% if model.errors.any? %>
  <div id="error_explanation" class="alert alert-warning">
      <ul class="mb-0">
          <% model.errors.full_messages.each do|message| %>
          <li><%= message %></li>
          <% end %>
      </ul>
  </div>
<% end %>

app/views/layouts/_flash_messages.html.erb
<% flash.each do|message_type,message| %>
<div class="alert alert-<%= message_type %>"><%= message %></div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang='ja'>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>simple-q-box</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css">

    <%= stylesheet_link_tag  'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js"></script>
    <script defer src="https://use.fontawesome.com/releases/v5.7.2/js/all.js"></script>
    
  </head>

  <body>
    <header>
      <% if logged_in? %>
  <nav class="navbar navbar-expand-sm navbar-light bg-white mb-2">
          <a class="navbar-brand" href="/"><img src="/assets/soso.png" alt="" width="100" ></a>　
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbar-Suppoted-content">
          <span class="navbar-toggler-icon"></span>        
        </button>
      <div class="collapse navbar-collapse justify-content-end" id ="navbar-Suppoted-content">    
        <ul class="navbar-nav nav-fill w-100">
          <li class="nav-item "><p class="d-inline">ログイン中のユーザー:</p><h3 class="d-inline"><%= link_to current_user.name,user_path(current_user) %></h3></li>
          <li class="nav-item"><h3><%= link_to'睡眠記録',cake_path(current_user)%></h3></li>
          <li class="nav-item"><h3><%= link_to '質問する',new_question_path %></h3></li>
        <li class="nav-item"><h3><%= link_to '質問検索' ,search_questions_path %></li>
        <li class="nav-item"><h3><%= link_to 'ログアウト', logout_path, method: :delete %></h3></li>
        </ul>
      </div>
   </nav>
  <% else %>
    <nav class="navbar navbar-expand-sm navbar-light bg-white">
      <a class="navbar-brand" href="/"><img src="/assets/soso.png" alt="" width="100" ></a>　　
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbar-Suppoted-content">
          <span class="navbar-toggler-icon"></span>        
        </button>
      <div class="collapse navbar-collapse justify-content-end" id ="navbar-Suppoted-content">    
        <ul class="navbar-nav">
          <li class="nav-item"><a href ="/questions/search" class="nav-link">質問検索</a></li>
          <li class="nav-item"><a href="/login" class="nav-link">ログイン</a></li>
          <li class="nav-item"><a href="/signup" class="nav-link">新規登録</a></li>
        </ul>
      </div>
    </nav>
    <h1 class="text-center text-danger">質問するには<%= link_to 'ログイン',login_path %>が必要です</h1>
    <h1 class="text-center text-warning">みんなで睡眠を改善しよう!</h1>
    <% end %>
    </header>
  
      <%= render 'layouts/flash_messages' %>
    
      <%= yield %>
 
  </body>
</html>

app/views/mokuhyous/edit.html.erb
<h1>Mokuhyous#edit</h1>
<p>Find me in app/views/mokuhyous/edit.html.erb</p>

app/views/mokuhyous/new.html.erb
 <div class="row">
      <div class="col-sm-8 offset-sm-2">
        <%= form_with(model: @mokuhyou,local: true)do|f|%>
        <%= render 'layouts/error_messages',model: @mokuhyou %>
          <div class="form-group">
            <h1 class="text-center text-warning">目標設定</h1>
            <%= f.text_area :content,class: 'form-control',rows: 7 %>
          </div>
          <div class="text-right text-warning"><p>文字数制限:255字</p></div>
          <%= f.submit '投稿',class: 'btn btn-primary btn-block'%>
        <% end %>
      </div>
  </div>    

app/views/password_resets/edit.html.erb
<h1>PasswordResets#edit</h1>
<p>Find me in app/views/password_resets/edit.html.erb</p>

app/views/password_resets/new.html.erb
<h1 class="text-center">パスワード変更</h1>
<div class="row">
    <div class="col-sm-6 offset-sm-3">
      <%= form_with(url: password_resets_path,scope: :password_reset,local: true)do |f| %>
      
        <div class="form-group">
         <%= f.label :email, 'メールアドレス'%>
         <%= f.text_field :email,class: 'form-control'%>
        </div>
        <%= f.submit '変更',class: 'btn btn-primary btn-block'%>
      <% end %>  
   </div>
</div>

app/views/questions/new.html.erb
 <div class="text-center"><h1>質問を投稿する</h1></div>
  
  <div class="row">
      <div class="col-sm-8 offset-sm-2">
        <%= form_with(model: @question,local: true)do|f|%>
        <%= render 'layouts/error_messages',model: @question %>
          <div class="form-group">
            <%= f.text_area :content,class: 'form-control',rows: 10 %>
          </div>
          <div class="text-right text-warning"><p>文字数制限:255字</p></div>
          <%= f.submit '投稿',class: 'btn btn-primary btn-block'%>
        <% end %>
      </div>
  </div>    

app/views/questions/search.html.erb
<div class="sesese">
  <%= form_with url: search_questions_path,method: :get,local: true do |f|%>
  <%= f.text_field :content %>
  <%= f.submit '検索' %> 
  <% end %>
    <div class="overflow-auto" style="height:700px; width:1640px;">
      <table class="table tbale-striped ">
  <thead>
    <tr class="bg-dark text-white">
      <th>質問</th>
      <th>投稿日</th>
      <th>ユーザー名</th>
      <th>閲覧数</th>
    </tr>
  </thead>
  <tbody>
    <% @questions.each do |questions| %>
      <tr class="bg-light">
      <td> <div class="iiii"><%= link_to simple_format(questions.content),question_path(questions) %></div></td>
        <td><%= questions.created_at.to_s(:datetime_jp) %></td>
        <td><%= questions.user.name%></td>
        <td><%= questions.impressions_count%></td>
      </tr>
    <% end %>
    
  </tbody>
</table>
</div>
 </div>

app/views/questions/show.html.erb
<div class="row mt-2"> 
  <div class=" col-sm-8 offset-2 text-center bg-light"> 
   <p class="d-inline text-success"><i class="fas fa-user"></i><%= link_to @question.user.name,user_path(@question.user) %></p> 
    <p class="d-inline"><i class="fas fa-eye"></i><%= @question.impressions_count %></p> 
    <div class="oooo"><%= simple_format(@question.content) %></div>
  </div> 
</div>
    <div class="row">
      <div class="col-sm-8 offset-sm-2 bg-light text-center">
      <div class="overflow-auto" style="height:500px; width:1300px;">
        <% @answers.order(created_at: :desc).each do |answer|%>
        <div class="nenene">
            <p class="d-inline"><i class="fas fa-user"></i><%= answer.name %></p>
            <p class="d-inline text-success"><i class="fas fa-calendar-alt"></i><%= answer.created_at.to_s(:datetime_jp) %></p>
            <%= simple_format(answer.content) %>
            </div>
        <% end %>
     </div>
     </div>
   </div>
   
    
    
    <div class="row mt-2">
      <div class="col-sm-6 offset-sm-3" >
        <%= form_with(model: @answer, local: true) do |f| %>
        <%= render 'layouts/error_messages',model: @answer %>
          <%= hidden_field_tag :question_id, @question.id %>
          <%= f.text_field :name, :value => "名無し"%>
          <%= f.text_area :content,class: 'form-control',rows: 3 %>
          <div class="text-right text-warning"><p>文字数制限:255字</p></div>
          <%= f.submit '投稿',class: 'btn btn-primary btn-block'%>
        <% end %>
      </div>
    </div>
   

app/views/toppages/index.html.erb
<div class="row">
      <div class="col-sm-6 bg-light">
        <h1 class="text-center">みんなの質問一覧(新着)</h1>
         <div class="overflow-auto " style="height:700px; width:820px;">
            <% @questions.order(created_at: 'DESC').each do |question|%>
           <ul>
             <li>
                <p class="text-success d-inline"><i class="fas fa-user"></i><%= link_to question.user.name,user_path(question.user) %></p>
                <p class="text-secondary d-inline"><i class="fas fa-calendar-alt"></i><%= question.created_at.to_s(:datetime_jp) %></p>
                <p class="d-inline"><i class="fas fa-eye"></i><%= question.impressions_count %></p>
                <div class="kikikiki"><%=link_to simple_format(question.content),question_path(question) %></div>
            </li>
          </ul>
          <% end %>
        </div>
     </div>
     
     <div class="col-sm-6 bg-light">
        <h1 class="text-center">閲覧数ランキング</h1>
         <div class="overflow-auto " style="height:700px; width:820px;">
           <% @rank_questions.each.with_index(1) do |question,i|%>
                <% if i==1 %>
                 <p class="d-inline text-warning">1</p><i class="fas fa-crown"></i><p class="text-success d-inline"><i class="fas fa-user"></i><%= link_to question.user.name,user_path(question.user) %></p>
                <p class="text-secondary d-inline"><i class="fas fa-calendar-alt"></i><%= question.created_at.to_s(:datetime_jp) %></p>
                <p class="d-inline"><i class="fas fa-eye"></i><%= question.impressions_count %></p>
                <div class="kekekeke"><%=link_to simple_format(question.content),question_path(question) %></div>
                <% elsif i==2 %>
                <p class="d-inline text-danger">2</p><i class="fas fa-crown"></i><p class="text-success d-inline"><i class="fas fa-user"></i><%= link_to question.user.name,user_path(question.user) %></p>
                <p class="text-secondary d-inline"><i class="fas fa-calendar-alt"></i><%= question.created_at.to_s(:datetime_jp) %></p>
                <p class="d-inline"><i class="fas fa-eye"></i><%= question.impressions_count %></p>
                <div class="kekekeke"><%=link_to simple_format(question.content),question_path(question) %></div>
                <% elsif i==3%>
                 <p class="d-inline text-success">3</p> <i class="fas fa-crown"></i><p class="text-success d-inline"><i class="fas fa-user"></i><%= link_to question.user.name,user_path(question.user) %></p>
                <p class="text-secondary d-inline"><i class="fas fa-calendar-alt"></i><%= question.created_at.to_s(:datetime_jp) %></p>
                <p class="d-inline"><i class="fas fa-eye"></i><%= question.impressions_count %></p>
                <div class="kekekeke"><%=link_to simple_format(question.content),question_path(question) %></div>
                <% else %>
                <%= i %><p class="text-success d-inline"><i class="fas fa-user"></i><%= link_to question.user.name,user_path(question.user) %></p>
                <p class="text-secondary d-inline"><i class="fas fa-calendar-alt"></i><%= question.created_at.to_s(:datetime_jp) %></p>
                <p class="d-inline"><i class="fas fa-eye"></i><%= question.impressions_count %></p>
                <div class="kekekeke"><%=link_to simple_format(question.content),question_path(question) %></div>
                <% end %>
          <% end %>
        </div>
     </div>
</div>
    
   

app/views/users/new.html.erb
    

<h1 class="text-center"> 新規登録フォーム</h1>
<div class="row">
    <div class="col-sm-6 offset-sm-3">
      <%= form_with(model: @user,local: true)do |f| %>
        <%= render 'layouts/error_messages',model: f.object %>
          <div class="form-group">
            <%= f.label :name,'名前'%>
            <%= f.text_field :name,class: 'form-control'%>
          </div>
          <div class="form-group">
            <%= f.label :email,'メールアドレス'%>
            <%= f.text_field :email,class: 'form-control'%>
          </div>
          <div class="form-group">
            <%=f.label :password,'パスワード'%>
            <%= f.password_field :password,class: 'form-control'%>
          </div>
          <div class="form-group">
            <%= f.label :password_confirmation, '確認用パスワード' %>
            <%= f.password_field :password_confirmation ,class: 'form-control' %>
          </div>
            <%= f.submit '登録',class: 'btn btn-primary btn-block' %>
      <% end %>
    </div>
</div>

app/views/users/show.html.erb
<% if current_user.id == @user.id %>
<div class="mypage">
  <div class="row">
      <div class="aa col-sm-6 bg-light ">
 　　　　　<table class="table table-warning">
　　　　　　<%= form_with(model: @sleep,local: true)do|f|%>
　　　　　　<%= render 'layouts/error_messages',model: f.object %>
   　　　 <thead>
        <tr>
            <th>睡眠時間（半角数字)</th>
            <th>試したこと</th>
            <th>感想</th>
            <th>気づき</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td><%=f.text_field :time %>時間</td>
            <td><%= f.text_area :try ,rows: 3%></td>
            <td><%= f.text_area :content ,rows: 3%></td>
            <td><%= f.text_area :content ,rows: 3%></td>
        </tr>
    </tbody>
　　　</table>
　　　<div class="karasu"><%= f.submit '投稿',class: 'btn btn-primary'%></div>
　　　 <% end %>

　　　     <div class="sososososo">
　　　<table class="table table-warning">
　　　    <h1 class="d-inline bg-white">最新の睡眠記録</h1>
   　　　 <thead>
        <tr>
            <th>睡眠時間</th>
            <th>試したこと</th>
            <th>感想</th>
            <th>気づき</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td><div class="todays_sleep"><%= @todays_sleep.time %></div></td>
            <td><div class="todays_sleep"><%= @todays_sleep.try %></div></td>
            <td><div class="todays_sleep"><%= @todays_sleep.impression %></div></td>
            <td><div class="todays_sleep"><%= @todays_sleep.content %></div></td>
        </tr>
    </tbody>
    </table>
　　　　</div>
　　　　<div class="mokuhyou">
　　　　    <h1 class="d-inline bg-white">今月の目標</h1>
　　　　 
　　　　    <h2 class="mokuhyou-2 text-warning">
         <% if @mokuhyou %>
              <%= @mokuhyou.content %>
              <% else %>
              目標を設定しましょう
              <% end %>
　　　　    </h2>
　　　　    
　　　　</div>
　　　　<%= link_to '目標を設定しよう',new_mokuhyou_path %>
　　

      </div>
     
      
      <div class="ii col-sm-4 offset-sm-1 bg-light text-centr">
        <h1 class="eeee text-center "><%= @user.name %>の質問一覧:質問数(<%= @questions.count %>)</h1>
          <div class="overflow-auto bg-light" style="height:700px; width:550px;">
    　　<% @questions.order(created_at: :desc).each do|question| %>
            <p class="text-secondary d-inline"><i class="fas fa-calendar-alt"></i><%= question.created_at.to_s(:datetime_jp) %></p>
            <p class="d-inline"><i class="fas fa-eye"></i><%= question.impressions_count %></p>
            <%= link_to "削除", question, method: :delete,data: {confirm: "本当に削除しますか？"}, class: 'btn btn-danger btn-sm' %>
           <div class="sa text-center"><%= link_to simple_format(question.content), question_path(question) %></div>
        <% end %>
  　　　　</div>
  　　</div>
  </div>
</div>
<% else %>

<div class="col-sm-6 offset-3">
        <h1 class="eeee text-center "><%= @user.name %>の質問一覧:質問数(<%= @questions.count %>)</h1>
          <div class="overflow-auto bg-light" style="height:700px; width:900px;">
    　　<% @questions.order(created_at: :desc).each do|question| %>
            <p class="text-secondary d-inline"><i class="fas fa-calendar-alt"></i><%= question.created_at.to_s(:datetime_jp) %></p>
            <p class="d-inline"><i class="fas fa-eye"></i><%= question.impressions_count %></p>
            
           <div class="sonson text-center"><%= link_to simple_format(question.content), question_path(question) %></div>
        <% end %>
  　　　　</div>
  　　</div>

　　<% end %>